### ISSUE TITLE
Scrape data sets and validate

### ISSUE THREAD

**Issue by matthew-sochor** [matthew-sochor/fish.io.ai#1]
Hey @MattGraz lets coordinate downloading and verifying images (i.e. deleting utter crap images and keeping pictures of fish and people holding fish) here:

Should be able to start from https://github.com/matthew-sochor/fish.io.ai/pull/2

You can make all_fish.csv with a newline separated list of fish you want, or just go crazy and run the script and pull images for everything.

Here is what I have so far (I'll continue to edit this as I go along):

*Downloaded:*
Carp
Walleye

*Verified:*
Carp (306 decent images)
Walleye (591)

**Comment by MattGraz** [comment]
Hey Matt, sounds good.  

Can you provide some context as to how long a run of the scraper takes for one fish?

**Comment by MattGraz** [comment]
I'll try to get some new fish started tonight!

**Comment by MattGraz** [comment]
I'm pulling some yellow perch now

**Comment by MattGraz** [comment]
@matthew-sochor @thenomemac- I've uploaded a new .zip file to the google driving containing a couple new folders: "yellow_perch_reduced" and "white_perch_reduce".  I did a second pass on the images and more aggressively took out images where the fish were not prevalent or junk.  This should help with the multinomial case

**Comment by MattGraz** [comment]
Closing as this is in relation to our first data pull.  I'll open a new one for the new scraping I did yesterday so we don't get our conversations intertwined.
