### ISSUE TITLE
Firefox dependency

### ISSUE THREAD

**Issue by MattGraz** [matthew-sochor/fish.io.ai#3]
> selenium.common.exceptions.WebDriverException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by thenomemac** [comment]
I've heard in the past Firefox is way easier to get configured for headless browser stuff.

**Comment by MattGraz** [comment]
#4
