### ISSUE TITLE
Filter Junk out of scraped fish images

### ISSUE THREAD

**Issue by MattGraz** [matthew-sochor/fish.io.ai#52]
@matthew-sochor @thenomemac, @becca, 

In the Google Drive, there are .zip files "assigned" to each of us to filter through fish.    I tossed 10 in each folder for organizational purposes.  I'm going to try to finish mine today, and I can try tapping into some of the other ones in your folders as well.

**Comment by MattGraz** [comment]
@matthew-sochor , @thenomemac 

After we do an initial round of junk, we

**Comment by matthew-sochor** [comment]
This is effectively done for the 17 primary fish.  If we want to continue in this vein we can make another issue, but for now I say:

good jorb, closing
