### ISSUE TITLE
Social media

### ISSUE THREAD

**Issue by MattGraz** [matthew-sochor/fish.io.ai#54]
I heard some talk that we secured some social media tags/handles last week? 

Can we post here what we have?  I can get them up and running and added to a readme

**Comment by MattGraz** [comment]
Facebook Pages:

https://www.facebook.com/What-Is-My-Fish-1651765048173841/
https://www.facebook.com/Whatismyfish-1244580678973777/

I snagged a couple pages ("Whatismyfish" as well as "What is my fish")

**Comment by thenomemac** [comment]
Did you get the pages as a group page or company page or whatever it's
called so we're not limited in number of followers and things.

**Comment by MattGraz** [comment]
Yep

**Comment by thenomemac** [comment]
Sweet. I took that screen cast and added narration so we can have that and
our press release linked so people know what it is

**Comment by MattGraz** [comment]
I think we should hold off on releasing the video for now.  I suspect over coming weeks that video will become obsolete very quickly as we add functional GPS, more specific DNR regulations, new logo, updated contact information, etc.  

It may make more sense to wait until we have a more stable aesthetic product before we start pushing video marketing too hard.  I think we can more effectively protect our brand once we have a more fully functional product.  

I don't think out webpage is feature functional enough to users yet for us to be advertising yet.

**Comment by MattGraz** [comment]
Barebones sites are all set up with images and such.  

Not sure how to best distribute passwords and such.  We'll talk tomorrow at work.
